"""Pydantic 2.x DTOs for the memory keystone public API."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

ScopeKind = Literal["project", "workspace", "brand", "agent", "skill", "global"]
EvidenceSourceKind = Literal["drawer", "observation"]
EntityKind = Literal["person", "project", "brand", "campaign", "post", "channel", "other"]


class SourceQualityHint:
    """Canonical source_quality values for write_observation callers."""

    operator: float = 1.0  # MC1: operator-approved action — maximum trust
    user: float = 1.0  # human-confirmed, highest trust
    consolidation: float = 0.9  # synthesized by LLM consolidation
    agent: float = 0.7  # generated by Artemis agent loop
    extractor: float = 0.5  # raw signal extraction, unverified


class Scope(BaseModel):
    """Identifies the memory namespace for a write or read operation."""

    model_config = ConfigDict(frozen=True)

    scope_kind: ScopeKind
    scope_id: str


class Source(BaseModel):
    """Provenance for a drawer write."""

    model_config = ConfigDict(frozen=True)

    source_kind: str
    source_id: str | None = None
    source_extra: dict[str, Any] | None = None


class ScopeRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    scope_kind: str
    scope_id: str
    display_name: str | None
    parent_scope_kind: str | None
    parent_scope_id: str | None
    created_at: datetime


class Drawer(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    scope_kind: str
    scope_id: str
    corpus_kind: str | None
    content: str
    content_hash: str
    source_kind: str
    source_id: str | None
    source_extra: dict[str, Any] | None
    owner_user_id: int | None
    captured_at: datetime


class Observation(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    scope_kind: str
    scope_id: str
    category: str
    content: str
    content_hash: str
    score: float
    hit_count: int
    source_quality: float
    user_confirmed: bool
    valid_from: datetime | None
    valid_until: datetime | None
    superseded_by: int | None
    owner_user_id: int | None
    created_at: datetime
    accessed_at: datetime
    # M2 fields
    confidence: float = 0.5
    supersedes: int | None = None
    evidence_count: int = 1


class Evidence(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    observation_id: int
    source_kind: str
    source_id: int
    source_quote: str | None
    weight: float
    created_at: datetime


class ScoredObservation(BaseModel):
    """An observation with retrieval-scoring metadata attached."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    scope_kind: str
    scope_id: str
    category: str
    content: str
    score: float
    hit_count: int
    source_quality: float
    user_confirmed: bool
    valid_from: datetime | None
    valid_until: datetime | None
    superseded_by: int | None
    owner_user_id: int | None
    created_at: datetime
    accessed_at: datetime
    # M2 fields
    confidence: float = 0.5
    supersedes: int | None = None
    evidence_count: int = 1
    # Retrieval scores
    final_score: float
    fts_rank: float
    semantic_sim: float
    recency: float
    graph_proximity: float = 0.0


# ── Graph layer DTOs (B4) ─────────────────────────────────────────────────────


class EntityRead(BaseModel):
    """Represents a named entity extracted from memory observations."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    entity_kind: str
    canonical_name: str
    name_slug: str
    scope_kind: str
    scope_id: str
    attributes: dict[str, Any] | None
    first_seen_at: datetime
    last_seen_at: datetime
    mention_count: int
    confidence: float
    superseded_by: int | None


class RelationRead(BaseModel):
    """Directed predicate-labelled edge between two entities.

    subject_name / subject_kind / object_name / object_kind are populated
    only when returned from get_entity_neighborhood (joined query).
    """

    model_config = ConfigDict(from_attributes=True)

    id: int
    subject_id: int
    predicate: str
    object_id: int
    evidence_observation_id: int | None
    weight: float
    confidence: float
    first_seen_at: datetime
    last_seen_at: datetime
    superseded_by: int | None
    # Set by neighborhood query (None when fetched without join)
    subject_name: str | None = None
    subject_kind: str | None = None
    object_name: str | None = None
    object_kind: str | None = None


class EntityNeighborhood(BaseModel):
    """An entity plus all of its relations within a given hop radius."""

    entity: EntityRead
    relations: list[RelationRead]


# ── Memory M2 — Conflict DTOs ─────────────────────────────────────────────────


class Conflict(BaseModel):
    """A detected contradiction between two observations."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    scope_id: str
    observation_a_id: int
    observation_b_id: int
    conflict_type: str
    detected_at: datetime
    resolution: str | None
    resolution_reason: str | None
    resolved_at: datetime | None
    resolved_by: str | None


class ConflictResolveRequest(BaseModel):
    """Body for POST /api/memory/conflicts/{id}/resolve."""

    resolution: str  # a_wins | b_wins | both_valid_different_scope | manual_review_needed
    reason: str | None = None
