"""Chat orchestration for Floating Artemis.

handle_turn() is the main entry point. It:
1. Checks the intent pre-router — if matched, returns structured response without LLM call.
2. Builds system prompt (persona + voice samples + page context + surfaces).
3. Loads message history from DB (token-budgeted).
4. Registers available tools (filtered by surface availability).
5. Runs the F1 agent loop with hook-based WS broadcasting.
6. Handles layer-3/4 tool yield: stores pending, broadcasts WS event, suspends.
7. Persists messages + token costs.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Literal, cast
from uuid import uuid4

from artemis.agent.client import AnthropicAdapter, ModelAdapter
from artemis.agent.hooks import HookRegistry
from artemis.agent.loop import run_turn, user_message
from artemis.agent.tools import ToolRegistry
from artemis.agent.types import (
    Message,
    RunResult,
    TextBlock,
    ToolCallRecord,
    ToolResultBlock,
    ToolUseBlock,
    Usage,
)
from artemis.costs.events import record_cost_event
from artemis.floating_artemis.authority import (
    AuthorizedToolRegistry,
    PendingConfirmation,
    confirmation_store,
)
from artemis.floating_artemis.context import (
    floating_session_id_var,
    floating_tool_use_id_var,
    floating_trusted_agent_id_var,
)
from artemis.floating_artemis.intent import IntentKind, classify_intent, handle_observability_intent
from artemis.floating_artemis.memory import inject_memory_context, write_turn_drawer
from artemis.floating_artemis.memory_read_cache import put as cache_put
from artemis.floating_artemis.personality import (
    ARTEMIS_PERSONA_CORE,
    load_agent_profile,
    select_voice_samples,
)
from artemis.floating_artemis.schemas import MemoryObservationDigest, MemoryReadEvent
from artemis.floating_artemis.session_scope import (
    is_personal_slack_dm_session,
    parse_history_cutover_at,
    resolve_surface_scope,
)
from artemis.floating_artemis.tool_registry import build_authorized_tool_registry
from artemis.providers import get_adapter
from artemis.providers.errors import MissingApiKeyError, UnknownProviderError
from artemis.routes.status import get_status
from artemis.trace.capture import capture_trace, elapsed_ms, start_timer
from artemis.ws.manager import ws_manager

logger = logging.getLogger(__name__)

# Artemis compatibility alias for tests that assert the historical core prompt.
_PERSONA_CORE = ARTEMIS_PERSONA_CORE


def _build_system_prompt(
    *,
    voice_samples: list[str],
    page_context: str | None,
    available_surfaces: list[str],
    persona_core: str | None = None,
    profile_text: str | None = None,
    display_name: str | None = None,
    agent_id: str = "artemis",
    recent_meeting_context: str | None = None,
    session_id: str = "",
    speaker_name: str | None = None,
    participants: list[str] | None = None,
    is_personal_slack_dm: bool = False,
    okr_reconcile_context: str | None = None,
    recent_outbound_texts: list[str] | None = None,
) -> str:
    profile = load_agent_profile("artemis")
    persona_core = profile.persona_core if persona_core is None else persona_core
    profile_text = profile.profile_text if profile_text is None else profile_text
    display_name = profile.display_name if display_name is None else display_name

    # Lead with the high-priority distilled persona rules.
    parts = [persona_core] if persona_core else []

    # Append the full personality profile as richer background detail.
    if profile_text:
        parts.append("## Full personality profile (background reference)\n" + profile_text)

    if voice_samples:
        samples_text = "\n".join(f'- "{line}"' for line in voice_samples)
        parts.append(
            "## Characteristic phrases (calibration only)\n"
            "These calibrate your register and rhythm. Never quote them verbatim or "
            "near-verbatim. Generate fresh lines in this spirit:\n" + samples_text
        )

    if page_context:
        parts.append(f"## Current operator context\n{page_context}")

    if available_surfaces:
        surfaces_str = ", ".join(sorted(available_surfaces))
        parts.append(f"## Available surfaces (your tools are gated by these)\n{surfaces_str}")

    # Recent meeting context (J6d): inject if a meeting ended within the last 4 hours.
    # H4: framed as LLM-generated inferences with provenance so action items
    # aren't treated as firm commitments.
    if recent_meeting_context:
        parts.append(
            "## Recent meeting summaries (LLM-generated by the meeting summarizer — "
            "treat as inferences)\n\n"
            "The following summaries were produced by the meeting_summarizer LLM after "
            "each meeting. Bullets and action_items reflect what the analyzer INFERRED "
            "from the transcript, not necessarily verbatim commitments.\n\n"
            "Before treating any action_item as a firm commitment by the user or another "
            "person:\n"
            "- For action_items with `owner` set: confirm with the user before acting\n"
            "- For action_items with `due` set: do not autonomously schedule reminders "
            "without user approval\n"
            "- If asked about a specific meeting decision, retrieve the raw transcript "
            "via granola tools rather than trusting the summary alone\n\n"
            f"{recent_meeting_context}"
        )

    # OKR reconcile context: injected when a live check-in breadcrumb exists for
    # this session's speaker.  Instructs Artemis to map the word-dump to KRs and
    # CALL update_okr_krs (layer-3 batch tool) — calling IS the proposal; the
    # tool suspends and waits for the operator's explicit 'go' before writing.
    if okr_reconcile_context:
        parts.append(okr_reconcile_context)

    # ── Human-voice nudge (agent-agnostic) ──────────────────────────────────
    # Applied to every agent on every turn.  Does NOT override persona content;
    # it reinforces structural habits that make any agent sound human.
    parts.append(
        "## Human communication rules (all agents, every turn)\n"
        "- Address people by their first name naturally when you know it — weave it "
        "in, don't open every message the same way.\n"
        "- Vary your sentence openings. Never start two consecutive messages the same way.\n"
        "- Never send canned, templated, or copy-pasted-sounding text.\n"
        "- Sound like a real person: concrete, warm where it fits, specific rather than generic."
    )

    # ── Acting vs. describing (agent-agnostic) ───────────────────────────────
    # Root fix for the recurring "agent narrates an action but nothing happens"
    # bug (Callie: 'Argus is on it' with no dispatch_research call; Artemis:
    # 'send tools aren't wired' when create_event/send_slack ARE in her toolset).
    # The infra works — the agents simply weren't calling their tools. This makes
    # tool-calling the only way to act, and forbids confabulating missing tools.
    parts.append(
        "## Acting means calling a tool (all agents, every turn)\n"
        "- To DO anything with an effect — schedule, send, dispatch, write, react — "
        "you must CALL the tool that does it. Describing the action in words is not "
        "performing it.\n"
        "- For side-effecting tools, calling is still safe: the system stages the call "
        "and hands you back a confirmation prompt to relay. Nothing executes until the "
        "operator confirms, so calling IS how you propose. Don't write a prose proposal "
        "instead of calling.\n"
        "- Never tell the operator something is done, or that you've started it (e.g. "
        '"it\'s on it", "I\'ve queued it"), unless you actually called the tool this turn.\n'
        '- Never claim a capability is missing or "not wired." If a tool is in your '
        "toolset, use it. If the call errors, report the actual error — don't invent a "
        "limitation."
    )

    # ── Anti-repetition: recent outbound messages ────────────────────────────
    # When the last few assistant messages in this session are available, inject
    # them so the LLM actively avoids repeating itself.  This prevents two
    # back-to-back channel-join welcomes from being verbatim identical.
    if recent_outbound_texts:
        quoted = "\n".join(f'- "{t}"' for t in recent_outbound_texts)
        parts.append(
            "## Your recent messages in this channel (do NOT repeat or closely echo these)\n"
            "These are your last outbound messages. Read them and deliberately vary your "
            "wording, structure, and opening so your next reply feels fresh and distinct:\n"
            + quoted
        )

    # Slack-originated session: establish the conversational context.
    if session_id.startswith("slack-"):
        if speaker_name:
            who = f" You are talking to {speaker_name}."
        else:
            # Say so explicitly rather than leaving a blank. With nothing here,
            # Callie addressed Josh as "Jon" -- the model filled the gap with the
            # only human it had ever been told about (2026-08-12).
            who = (
                " You do NOT know who is speaking. Do not guess a name, and do "
                "not assume it is Jon."
            )
        if participants:
            # Who is in the room, resolved from verified Slack ids. Prefer these
            # people over any directory name-search: asked to "tell Josh the top
            # signals" while Josh Mukai sat in that very channel, Callie searched
            # the whole company and offered "Josh Smith (0.9 confidence)".
            who += (
                " People in this conversation: "
                + ", ".join(participants)
                + ". When someone refers to a person by first name, resolve it "
                "against THIS list first -- these are verified participants. Only "
                "search the wider directory if nobody here matches."
            )
        parts.append(
            "**You are responding in Slack.** The operator @-mentioned you directly. "
            "**Assume they are addressing you and respond on-topic.** "
            'Do not ask "Are you talking to me?" — they are. '
            "Be concise; Slack rewards short replies. "
            "**Do NOT use markdown tables** (`| Field | Value |` pipe-table syntax) — "
            "Slack renders them as raw pipes and dashes. "
            "Use **bold labels** with short bullet lines or plain sentences instead." + who
        )
        if is_personal_slack_dm and agent_id == "artemis":
            parts.append(
                "## Slack DM scope\n"
                "This 1:1 Slack DM is for personal support, app/ops issues, and upgrades. "
                "You are Jon's orchestrator and personal partner here. "
                "Do not volunteer marketing in this DM. Marketing is Callie's lane and only "
                "comes here if Jon explicitly asks."
            )

    return "\n\n".join(parts)


async def get_recent_summaries_with_provenance(
    db_session: Any | None, hours: int = 4
) -> list[dict[str, Any]]:
    """Return recent meeting summaries with explicit LLM-provenance metadata (H4).

    Each item is `{meeting_id, title, summary, action_items, provenance}`.
    `provenance.source="llm_meeting_summarizer"`, `legacy_format=True` when the
    stored `action_items` would not pass the current Pydantic shape.

    Lossless invariant: existing rows are NEVER mutated — `legacy_format` is a
    read-time marker only.
    """
    import artemis.db as _db
    from artemis.meetings.summarizer import get_recent_summaries
    from artemis.meetings.summary_schemas import validate_existing

    async def _fetch(session: Any) -> list[Any]:
        return cast(list[Any], await get_recent_summaries(session, hours=hours))

    if db_session is not None:
        rows = await _fetch(db_session)
    else:
        async with _db.SessionLocal() as session:
            rows = await _fetch(session)

    result: list[dict[str, Any]] = []
    for row in rows:
        is_valid, _ = validate_existing(row.action_items)
        result.append(
            {
                "meeting_id": row.granola_id,
                "title": row.title,
                "summary": row.summary,
                "action_items": row.action_items,
                "provenance": {
                    "source": "llm_meeting_summarizer",
                    "generated_at": row.created_at.isoformat() if row.created_at else None,
                    "transcript_truncated_at_chars": 6000,
                    "legacy_format": not is_valid,
                },
            }
        )
    return result


async def _get_recent_meeting_context(db_session: Any | None) -> str | None:
    """Return a one-liner summary of meetings ended in the last 4 hours, or None.

    Used by handle_turn to inject meeting context into the system prompt so
    Artemis is aware of what Jon just finished without being told. H4 framing
    in `_build_system_prompt` flags these as LLM inferences with provenance.
    """
    try:
        items = await get_recent_summaries_with_provenance(db_session, hours=4)
        if not items:
            return None

        lines: list[str] = []
        for item in items:
            summary_text = item["summary"]
            bullet_lines = [
                line.strip() for line in summary_text.splitlines() if line.strip().startswith("-")
            ][:3]
            bullets_short = " ".join(bullet_lines) if bullet_lines else summary_text[:200]
            legacy = " [legacy_format]" if item["provenance"]["legacy_format"] else ""
            lines.append(f'You just finished "{item["title"]}"{legacy}. Summary: {bullets_short}')
        return "\n".join(lines)
    except Exception:
        logger.debug("Failed to fetch recent meeting context", exc_info=True)
        return None


async def _get_okr_reconcile_context(
    speaker_id: str | None,
    db_session: Any | None,
) -> str | None:
    """Return OKR-reconcile system context if a live check-in breadcrumb exists.

    When the Friday check-in fires, it persists a breadcrumb keyed to Jon's
    Slack user ID.  While that breadcrumb is live (not expired, not completed),
    we inject context into the system prompt so the next DM reply gets mapped
    to specific KRs and `stage_okr_updates` is called.  Staging does NOT apply;
    it records the proposed updates on the breadcrumb and pauses for the
    operator's explicit 'go' (applied server-side in route_inbound).  This is
    the path that works on the claude-code subscription surface, where the
    layer-3 write tools (update_okr_kr/update_okr_krs) are not reachable.

    Returns None when no live breadcrumb exists (normal DM path, no injection).
    Failure-isolated: any DB/import error returns None so chat is never broken.
    """
    if not speaker_id:
        return None
    try:
        import artemis.db as _db
        from artemis.proactivity.repository import get_live_okr_checkin_breadcrumb

        if db_session is not None:
            crumb = await get_live_okr_checkin_breadcrumb(db_session, speaker_id)
        else:
            async with _db.SessionLocal() as session:
                crumb = await get_live_okr_checkin_breadcrumb(session, speaker_id)

        if crumb is None:
            return None

        # Build the reconcile context block from the snapshot.
        snapshot = crumb.kr_snapshot or []
        if not snapshot:
            kr_list = "(no KR snapshot available)"
        else:
            lines = []
            for entry in snapshot:
                obj_title = str(entry.get("objective_title") or "").strip()
                kr_title = str(entry.get("kr_title") or "").strip()
                prog = int(entry.get("prog") or 0)
                target = str(entry.get("target_text") or "").strip()
                target_str = f" (target: {target})" if target else ""
                lines.append(
                    f"  KR {entry.get('kr_id')}: *{obj_title}* > *{kr_title}* "
                    f"— currently {prog}%{target_str}"
                )
            kr_list = "\n".join(lines)

        return (
            "## OKR check-in reconcile context\n\n"
            "You ran a Friday OKR check-in earlier. The operator's reply is their "
            "word-dump of what they moved this week. Your job:\n\n"
            "1. Engage with the substance of what they describe (be helpful, warm, on-topic).\n"
            "2. ALSO: map concrete accomplishments to SPECIFIC KRs from the snapshot below. "
            "Do NOT invent KRs or fabricate progress. If something doesn't map, say so.\n"
            "3. **CALL `stage_okr_updates` with ALL mapped updates in a single call**, "
            f"passing speaker_id={speaker_id!r} and updates=[{{kr_id, progress, basis, bullet}}, ...]. "
            "Stage everything in one call, not one call per KR.\n"
            "   - `stage_okr_updates` does NOT apply anything and writes ZERO KR rows. "
            "It records the proposed updates and pauses for the operator's explicit 'go'. "
            "After you stage, tell the operator what you staged and ask them to say 'go' "
            "to apply or 'no' to discard. The apply happens server-side after 'go'.\n"
            "   - Do NOT describe the updates only in prose and wait. Make the "
            "`stage_okr_updates` call so the operator can confirm.\n"
            "   - Never claim `stage_okr_updates` is unavailable — it is wired and is the "
            "supported check-in path on this surface. (The layer-3 `update_okr_kr` / "
            "`update_okr_krs` write tools are not reachable here; use `stage_okr_updates`.)\n"
            "4. Each staged update MUST cite the operator's own words as `basis`. "
            "Empty-basis and unknown-KR items are dropped automatically.\n"
            "   For each update, also include a concise `bullet` field: a SHORT one-line "
            "scannable summary of the accomplishment, grounded in the operator's own words "
            "(no fabrication, no new claims). Example: if the operator said 'brand hub is "
            "live on our server with all guidelines', the bullet might be 'Brand hub live "
            "on server with version-controlled guidelines'. If you are unsure how to condense "
            "it, fall back to a trimmed `basis`. The bullet is shown to the operator in the "
            "proposal (before 'go') and written to the KR's done_bullets on apply.\n"
            "5. PREFER STAGING. If the message describes ANY work / accomplishments / "
            "progress, treat it as a word-dump and `stage_okr_updates` — even if it opens "
            "or closes with a courtesy like 'hi', 'thanks', or 'thank you'. A polite "
            "greeting wrapped around a work update is NOT a sign-off.\n"
            "   Only call `complete_okr_checkin` (with "
            f"speaker_id={speaker_id!r}) when the message is PURELY a closing "
            "acknowledgement with NO reportable work (e.g. just 'that\\'s all',  "
            "'nothing else', 'done for now'), OR is clearly an unrelated new topic. When "
            "in doubt, stage rather than close. After a genuine close, do not keep "
            "injecting reconcile context.\n\n"
            f"Current KR snapshot:\n{kr_list}\n\n"
            "Reconcile their word-dump to these KRs, cite their words as basis, "
            "and CALL `stage_okr_updates` to stage the batch — then ask the operator "
            "to say 'go' to apply or 'no' to discard."
        )
    except Exception:
        logger.debug("_get_okr_reconcile_context failed — skipping injection", exc_info=True)
        return None


# ── Tool registry factory ─────────────────────────────────────────────────────


def _build_tool_registry(
    available_surfaces: set[str],
    agent_id: str | None = None,
    speaker_id: str | None = None,
) -> AuthorizedToolRegistry:
    return build_authorized_tool_registry(
        available_surfaces,
        agent_id=agent_id,
        speaker_id=speaker_id,
    )


# ── WS event helpers ──────────────────────────────────────────────────────────


async def _broadcast(session_id: str, event: dict[str, Any]) -> None:
    room = f"fa:{session_id}"
    await ws_manager.broadcast(room, event)


async def _emit_memory_read_event(
    session_id: str,
    inp: dict[str, Any],
    agent_id: str | None = None,
) -> None:
    """Re-run search_observations after query_memory completes to emit the provenance event.

    This is a secondary lightweight retrieval — results are used only for the
    inspector, never shown as the tool response. If retrieval fails, we still
    emit a MemoryReadEvent with an empty list so the inspector clears stale state.

    M3: ``agent_id`` is enforced via ``_enforce_agent_scope_set`` — the provenance
    re-run is subject to the same scope allowance as the primary query so the
    inspector cannot reveal scopes the agent may not read.
    """
    import datetime

    digests: list[MemoryObservationDigest] = []
    try:
        import artemis.db as _db
        from artemis.floating_artemis.memory import _enforce_agent_scope_set
        from artemis.memory.retrieval import search_observations
        from artemis.memory.schemas import Scope

        query = inp.get("query", "")
        scope = inp.get("scope", "global:global")
        limit = int(inp.get("limit", 10))
        scope_kind, scope_id = scope.split(":") if ":" in scope else (scope, "default")

        # M3: enforce agent allowance before querying.
        _agent_id = agent_id or ""
        enforced = _enforce_agent_scope_set(
            _agent_id, [Scope(scope_kind=scope_kind, scope_id=scope_id)]
        )
        results = []
        if enforced:
            async with _db.SessionLocal() as db_session:
                results = await search_observations(
                    db_session,
                    scope_set=enforced,
                    query=query,
                    limit=limit,
                )

        for r in results:
            text_trunc = r.content[:200] if len(r.content) > 200 else r.content
            digests.append(
                MemoryObservationDigest(
                    id=r.id,
                    drawer=f"{r.scope_kind}:{r.scope_id}",
                    text=text_trunc,
                    score=r.final_score,
                    sources=[r.scope_kind],
                    why=None,
                )
            )
    except Exception:
        logger.debug("Memory read event retrieval failed; emitting empty event", exc_info=True)

    turn_id = datetime.datetime.now(datetime.UTC).isoformat()
    mem_event = MemoryReadEvent(
        session_id=session_id,
        turn_id=turn_id,
        observations=digests,
    )
    cache_put(mem_event)
    await _broadcast(session_id, mem_event.model_dump())


# ── Provider resolution ────────────────────────────────────────────────────────


async def _resolve_adapter(
    *,
    session_id: str,
    db_session: Any | None,
) -> ModelAdapter | str:
    """Build the appropriate ModelAdapter for the session's provider/model.

    Returns a ModelAdapter on success.
    Returns a plain str error message when the adapter cannot be built (e.g.
    missing API key) — the caller must handle this case and broadcast a
    floating_artemis.failed event.
    Falls back to AnthropicAdapter when no provider is set on the session.
    """
    # Default chain: try the session's chosen provider first, then fall back
    # through subscription/local providers that don't need a key, so an
    # operator with no API keys can still chat via Claude Max / ChatGPT Plus /
    # LM Studio without seeing a 401.
    provider_id: str | None = None
    model_id: str | None = None

    try:
        import artemis.db as _db
        from artemis.floating_artemis.repository import get_session_by_id

        if db_session is not None:
            row = await get_session_by_id(db_session, session_id)
        else:
            async with _db.SessionLocal() as session:
                row = await get_session_by_id(session, session_id)

        if getattr(row, "provider", None):
            provider_id = row.provider
        if getattr(row, "model", None):
            model_id = row.model
    except Exception:
        # Session not found or DB error — use the default chain
        pass

    # Provider preference order: session-chosen → claude-code → codex →
    # lm-studio → anthropic (the original default; will raise if no API key
    # so the operator-visible message points to Integrations).
    candidates: list[str] = []
    if provider_id:
        candidates.append(provider_id)
    candidates += [
        p for p in ("claude-code", "codex", "lm-studio", "anthropic") if p not in candidates
    ]

    last_error: Exception | None = None
    for candidate in candidates:
        try:
            kwargs: dict[str, Any] = {}
            if model_id and candidate == provider_id:
                kwargs["default_model"] = model_id
            return get_adapter(candidate, **kwargs)
        except (MissingApiKeyError, UnknownProviderError) as exc:
            last_error = exc
            continue
        except Exception as exc:  # e.g. MissingCliBinaryError for CLI providers
            last_error = exc
            continue

    return (
        "No LLM provider is available. Open Integrations to add an API key, "
        "or install the Claude Code or Codex CLI to chat with your subscription. "
        f"(last error: {last_error})"
    )


# ── Turn result ───────────────────────────────────────────────────────────────


@dataclass
class TurnResult:
    session_id: str
    response_text: str | None
    stop_reason: str
    usage: Usage
    pending_tool_use_id: str | None = None  # set when yielded for layer-3/4 confirmation
    intent_shortcut: bool = False


@dataclass(frozen=True)
class _SessionContext:
    metadata: dict[str, Any]
    available_surfaces: set[str]
    is_personal_slack_dm: bool
    agent_id: str


def _serialize_blocks(
    blocks: list[TextBlock | ToolUseBlock | ToolResultBlock],
) -> list[dict[str, Any]]:
    return [block.to_api() for block in blocks]


async def _load_session_context(
    *,
    session_id: str,
    db_session: Any | None,
    all_surfaces: set[str],
    trusted_agent_id: str | None = None,
) -> _SessionContext:
    """Load session context.

    Parameters
    ----------
    trusted_agent_id:
        When provided (web-turn path), this value GOVERNS tool/memory gating — it
        overrides the persisted session metadata.  Derived server-side from the
        live caller's verified identity, so it cannot be spoofed via stale metadata.
        When None (Slack path, tests, resume path), falls back to persisted metadata
        with a FAIL-CLOSED default of "callie" (not "artemis").
    """
    metadata: dict[str, Any] = {}
    try:
        import artemis.db as _db
        from artemis.floating_artemis.repository import get_session_by_id

        if db_session is not None:
            row = await get_session_by_id(db_session, session_id)
        else:
            async with _db.SessionLocal() as session:
                row = await get_session_by_id(session, session_id)
        metadata_raw = getattr(row, "metadata_", {}) or {}
        if isinstance(metadata_raw, dict):
            metadata = metadata_raw
    except Exception:
        logger.debug("Could not load session metadata for session %s", session_id, exc_info=True)

    if trusted_agent_id is not None:
        # Live-identity-derived: use directly, normalise only.
        agent_id = (
            trusted_agent_id.strip().lower()
            if isinstance(trusted_agent_id, str) and trusted_agent_id.strip()
            else "callie"
        )
        logger.debug(
            "_load_session_context: using trusted_agent_id=%r for session %s (overrides metadata)",
            agent_id,
            session_id,
        )
    else:
        # Slack path / tests / resume: read from persisted metadata.
        # FAIL-CLOSED: default to "callie" (marketing-only), never "artemis".
        raw_agent_id = (
            metadata.get("agent_id", "callie") if isinstance(metadata, dict) else "callie"
        )
        agent_id = (
            raw_agent_id.strip().lower()
            if isinstance(raw_agent_id, str) and raw_agent_id.strip()
            else "callie"
        )
    scoped_surfaces = resolve_surface_scope(
        all_surfaces=all_surfaces,
        session_id=session_id,
        metadata=metadata,
    )
    return _SessionContext(
        metadata=metadata,
        available_surfaces=scoped_surfaces,
        is_personal_slack_dm=is_personal_slack_dm_session(session_id, metadata),
        agent_id=agent_id,
    )


def _collect_tools_used(result: RunResult) -> list[str]:
    """Return the deduped, ordered list of tool names invoked during a turn.

    Merges two sources, because the two provider paths surface tool calls in
    completely different places (OBS-1):

    - **Anthropic path**: ``run_turn`` executes tool_use rounds itself, so
      ``ToolUseBlock``s land directly in ``result.messages``. Scanned here
      exactly as before this fix — this source, and this path, are unchanged.
    - **claude-code MCP path** (Builder / Floating Artemis — i.e. every
      Slack-facing agent: Callie, Kai, Artemis): the CLI runs its OWN internal
      tool loop inside the subprocess and returns only a final text result,
      so no ``ToolUseBlock`` ever reaches ``result.messages`` for this path —
      that gap is the whole reason ``agent_traces.tools_used`` was ``[]`` for
      30+ days straight. ``run_turn`` recovers this from the adapter's
      stream-json parse and threads it through
      ``result.metadata["tool_calls"]`` (see ``artemis/agent/loop.py`` and
      ``artemis/providers/claude_code/adapter.py::_parse_stream_json``);
      merged in below.

    In practice exactly one source is non-empty for any given turn (a turn
    uses exactly one adapter), but both are merged the same way regardless:
    first-occurrence-wins dedup, in encounter order.

    A tool name that failed at least once is recorded as ``"<name>:error"``
    rather than a bare name. There is no separate error column to use instead
    — no migration; ``agent_traces.tools_used`` stays the ``JSONB`` array of
    strings it already is — and a name-only list would make a tool that ran
    and errored look identical to a clean success, which is exactly the
    failure mode this instrument exists to catch (a tool that "ran" and
    errored is the case that matters most; see the OBS-1 brief).
    """
    errors: dict[str, bool] = {}

    for msg in result.messages:
        if msg.role != "assistant":
            continue
        for block in msg.content:
            if isinstance(block, ToolUseBlock) and block.name not in errors:
                errors[block.name] = False

    tool_calls = cast(list[ToolCallRecord], result.metadata.get("tool_calls") or [])
    for call in tool_calls:
        if call.name not in errors:
            errors[call.name] = call.is_error
        elif call.is_error:
            errors[call.name] = True

    return [f"{name}:error" if is_error else name for name, is_error in errors.items()]


# ── Main entry point ──────────────────────────────────────────────────────────


async def handle_turn(
    *,
    session_id: str,
    user_text: str,
    reasoning_effort: str | None = None,
    speed_tier: str | None = None,
    adapter: ModelAdapter | None = None,
    owner_user_id: int | None = None,
    speaker_name: str | None = None,
    speaker_id: str | None = None,
    participants: list[str] | None = None,
    db_session: Any | None = None,
    trusted_agent_id: str | None = None,
) -> TurnResult:
    """Run one user turn for the given Floating Artemis session.

    Parameters
    ----------
    session_id:
        The floating_artemis_sessions.session_id key.
    user_text:
        The operator's message.
    adapter:
        Optional ModelAdapter override (for tests). Defaults to AnthropicAdapter.
    owner_user_id:
        Owner user ID for surface filtering and memory queries.
    speaker_name:
        Display name of the person speaking (e.g. resolved from the Slack user
        cache for inbound DMs). Threaded into the system prompt so Artemis
        addresses the operator by name. None for the web UI / unknown speakers.
    speaker_id:
        Stable platform identifier for the speaker (e.g. Slack user ID such as
        ``U01ABCDEF``).  Used alongside ``speaker_name`` for per-person memory
        attribution.  None for the web UI / unknown speakers.
    db_session:
        Optional SQLAlchemy AsyncSession (for tests). If None, a new session is
        opened from SessionLocal per DB operation.
    trusted_agent_id:
        M3 identity binding: when set, this value GOVERNS scope gating for the
        entire turn, overriding whatever agent_id is persisted in session metadata.
        Must be derived server-side from the live caller's verified identity (see
        resolve_agent_id_from_email).  When None the session metadata is used with
        a fail-closed default of "callie" (not "artemis").
        - Web-turn path: always set by the route handler from the CF-Access identity.
        - Slack path: None (session metadata is server-authored by route_inbound).
        - Tests: set explicitly to the identity under test.
    """
    # ── 1. Intent shortcut ────────────────────────────────────────────────────
    intent = classify_intent(user_text)
    if intent.kind != IntentKind.NONE:
        shortcut = await handle_observability_intent(intent, owner_user_id=owner_user_id)
        if shortcut is not None:
            await _broadcast(
                session_id,
                {"type": "floating_artemis.turn_started", "session_id": session_id},
            )
            response = shortcut.get("response", "")
            await _broadcast(
                session_id,
                {"type": "floating_artemis.message", "session_id": session_id, "text": response},
            )
            await _broadcast(
                session_id,
                {"type": "floating_artemis.turn_complete", "session_id": session_id},
            )
            # Persist both user message and assistant response
            shortcut_user_msg_id = await _persist_messages(
                session_id=session_id,
                user_text=user_text,
                assistant_text=response,
                user_content=None,
                assistant_content=None,
                usage=Usage(),
                db_session=db_session,
            )
            # M3: write conversation drawer for intent-shortcut turns too (failure-isolated)
            if shortcut_user_msg_id is not None and response:
                try:
                    await write_turn_drawer(
                        user_msg_id=shortcut_user_msg_id,
                        user_text=user_text,
                        assistant_text=response,
                        speaker_name=speaker_name,
                        speaker_id=speaker_id,
                    )
                except Exception:
                    logger.warning(
                        "M3 turn-drawer write failed (shortcut) session_id=%s msg_id=%s",
                        session_id,
                        shortcut_user_msg_id,
                        exc_info=True,
                    )
            return TurnResult(
                session_id=session_id,
                response_text=response,
                stop_reason="end_turn",
                usage=Usage(),
                intent_shortcut=True,
            )

    # ── 2. Get current surfaces ───────────────────────────────────────────────
    try:
        status = await get_status()
        surfaces_list = status.get("available_surfaces", []) if isinstance(status, dict) else []
        all_surfaces: set[str] = set(surfaces_list if isinstance(surfaces_list, list) else [])
    except Exception:
        all_surfaces = set()
    session_ctx = await _load_session_context(
        session_id=session_id,
        db_session=db_session,
        all_surfaces=all_surfaces,
        trusted_agent_id=trusted_agent_id,
    )
    available_surfaces = session_ctx.available_surfaces

    # ── 3. Gather system prompt ingredients (built after history loads in 4a) ──
    agent_profile = load_agent_profile(session_ctx.agent_id)
    # Use the profile-sourced voice corpus (deterministic per session_id).
    voice_samples = select_voice_samples(
        session_id=session_id,
        k=4,
        voice_corpus=agent_profile.voice_corpus,
    )
    page_context_text = await _get_page_context_text(session_id=session_id, db_session=db_session)
    recent_meeting_ctx = await _get_recent_meeting_context(db_session)

    # Part A: OKR reconcile context — only for personal Slack DM turns when a
    # live check-in breadcrumb exists for the speaker.  No-ops for all other turns.
    okr_reconcile_ctx: str | None = None
    if session_ctx.is_personal_slack_dm and speaker_id:
        okr_reconcile_ctx = await _get_okr_reconcile_context(speaker_id, db_session)

    # ── 4. Load history ───────────────────────────────────────────────────────
    history = await _load_message_history(
        session_id=session_id,
        db_session=db_session,
        session_metadata=session_ctx.metadata,
    )

    # ── 4a. Anti-repetition: rebuild system prompt with recent outbound texts ─
    # Extract the last 3-5 assistant text blocks from history so the LLM can
    # actively avoid repeating itself.  Two back-to-back channel-join welcomes
    # will have different recent_outbound_texts even if both start from a cold
    # session, because the first joiner's turn writes to history before the
    # second fires (background tasks run serially per worker).  When history is
    # empty (true cold start) the list is empty and the block is omitted.
    recent_outbound_texts: list[str] = []
    for msg in reversed(history):
        if msg.role == "assistant":
            for block in msg.content:
                if isinstance(block, TextBlock) and block.text.strip():
                    recent_outbound_texts.append(block.text.strip())
                    break  # one text per message is enough
        if len(recent_outbound_texts) >= 4:
            break
    recent_outbound_texts.reverse()  # chronological order for readability

    # Rebuild system prompt with the anti-repetition context now available.
    system_prompt = _build_system_prompt(
        voice_samples=voice_samples,
        page_context=page_context_text,
        available_surfaces=sorted(available_surfaces),
        persona_core=agent_profile.persona_core,
        profile_text=agent_profile.profile_text,
        display_name=agent_profile.display_name,
        agent_id=agent_profile.agent_id,
        recent_meeting_context=recent_meeting_ctx,
        session_id=session_id,
        speaker_name=speaker_name,
        participants=participants,
        is_personal_slack_dm=session_ctx.is_personal_slack_dm,
        okr_reconcile_context=okr_reconcile_ctx,
        recent_outbound_texts=recent_outbound_texts if recent_outbound_texts else None,
    )

    # ── 4b. M4: inject memory context into system prompt ─────────────────────
    # Augment after history load so we can use recent turns as retrieval context.
    system_prompt = await inject_memory_context(
        system_prompt,
        user_text,
        history,
        session_id,
        agent_id=session_ctx.agent_id,
        speaker_name=speaker_name,
        speaker_id=speaker_id,
    )

    if adapter is None:
        resolved = await _resolve_adapter(session_id=session_id, db_session=db_session)
        if isinstance(resolved, str):
            # Provider misconfigured — surface inline, do not crash
            await _broadcast(
                session_id,
                {
                    "type": "floating_artemis.failed",
                    "session_id": session_id,
                    "error": resolved,
                },
            )
            return TurnResult(
                session_id=session_id,
                response_text=None,
                stop_reason="provider_error",
                usage=Usage(),
            )
        adapter = resolved

    # ── 5. Build tool registry ────────────────────────────────────────────────
    # M3: pass agent_id into the registry builder so query_memory is gated to
    # this session's agent allowance.
    # speaker_id is the Slack user id resolved from the inbound event. It
    # authorizes Kai's flag_catalog_gap and is bound into that tool as a closure
    # value, so tool input cannot spoof the requester. None denies (fail-closed).
    auth_registry = _build_tool_registry(
        available_surfaces,
        agent_id=session_ctx.agent_id,
        speaker_id=speaker_id,
    )

    from artemis.providers.claude_code.adapter import ClaudeCodeAdapter

    is_claude_code_with_tools = isinstance(adapter, ClaudeCodeAdapter)

    # Claude Code's MCP path runs tools in a subprocess and cannot surface the
    # in-process layer-3/4 confirmation yield, so we only expose auto-invoke
    # tools there. Other providers keep the full intercepting registry.
    if is_claude_code_with_tools:
        tool_registry = _build_auto_invoke_tool_registry(
            auth_registry, session_id, agent_id=session_ctx.agent_id
        )
    else:
        # Build a plain ToolRegistry that wraps the authorized one for the loop.
        # Layer 3/4 tools get wrapped so we can intercept before execution.
        tool_registry = _build_intercepting_tool_registry(
            auth_registry, session_id, agent_id=session_ctx.agent_id
        )

    # ── 6. Broadcast turn started ─────────────────────────────────────────────
    await _broadcast(
        session_id, {"type": "floating_artemis.turn_started", "session_id": session_id}
    )

    # ── 7. Append user message and run ────────────────────────────────────────
    messages = history + [user_message(user_text)]

    # Set up hooks for broadcasting events
    hooks = HookRegistry()

    async def on_message_hook(msg: Message) -> None:
        if msg.role == "assistant":
            for block in msg.content:
                if isinstance(block, TextBlock):
                    await _broadcast(
                        session_id,
                        {
                            "type": "floating_artemis.message",
                            "session_id": session_id,
                            "text": block.text,
                        },
                    )

    async def before_tool_hook(payload: dict[str, Any]) -> None:
        await _broadcast(
            session_id,
            {
                "type": "floating_artemis.tool_started",
                "session_id": session_id,
                "tool": payload.get("name"),
                "tool_use_id": payload.get("tool_use_id"),
            },
        )

    async def after_tool_hook(payload: dict[str, Any]) -> None:
        await _broadcast(
            session_id,
            {
                "type": "floating_artemis.tool_completed",
                "session_id": session_id,
                "tool": payload.get("name"),
                "tool_use_id": payload.get("tool_use_id"),
                "is_error": payload.get("is_error", False),
            },
        )

    hooks.on("on_message", on_message_hook)
    hooks.on("before_tool", before_tool_hook)
    hooks.on("after_tool", after_tool_hook)

    session_token = floating_session_id_var.set(session_id)
    # SECURITY (M3): bind the subprocess's memory scope to the TRUSTED agent_id
    # (session_ctx.agent_id derives from the live caller's identity), not persisted
    # session metadata — so a non-owner turn on an owner session can't read owner memory.
    trusted_token = floating_trusted_agent_id_var.set(session_ctx.agent_id)
    _turn_start = start_timer()
    try:
        result = await run_turn(
            adapter=adapter,
            messages=messages,
            tools=tool_registry,
            system=system_prompt,
            reasoning_effort=reasoning_effort,
            speed_tier=speed_tier,
            hooks=hooks,
        )
    except _PendingConfirmationError as pending_exc:
        # A layer-3/4 tool was encountered — yield to operator.
        pending = confirmation_store.get(pending_exc.tool_use_id)
        if pending is not None:
            pending.prior_tool_results = [
                block.to_api() for block in getattr(pending_exc, "prior_tool_results", [])
            ]

        await _broadcast(
            session_id,
            {
                "type": "floating_artemis.tool_pending",
                "session_id": session_id,
                "tool_use_id": pending_exc.tool_use_id,
                "tool_name": pending_exc.tool_name,
                "tool_input": pending_exc.tool_input,
                "layer": pending_exc.layer,
            },
        )
        # Persist messages up to this point (user message + assistant tool_use turn)
        await _persist_messages(
            session_id=session_id,
            user_text=user_text,
            assistant_text=None,
            user_content=None,
            assistant_content=_serialize_blocks(pending_exc.assistant_message.content),
            usage=getattr(pending_exc, "usage", Usage()),
            db_session=db_session,
        )
        # Extract text from the assistant's proposal message so Slack/other
        # non-WS surfaces can post it without needing WS broadcast access.
        _proposal_texts = [
            b.text for b in pending_exc.assistant_message.content if isinstance(b, TextBlock)
        ]
        _proposal_text = " ".join(_proposal_texts) if _proposal_texts else None
        return TurnResult(
            session_id=session_id,
            response_text=_proposal_text,
            stop_reason="tool_pending",
            usage=Usage(),
            pending_tool_use_id=pending_exc.tool_use_id,
        )
    except Exception as exc:
        logger.exception("handle_turn failed session_id=%s", session_id)
        await _broadcast(
            session_id,
            {"type": "floating_artemis.failed", "session_id": session_id, "error": str(exc)},
        )
        raise
    finally:
        floating_trusted_agent_id_var.reset(trusted_token)
        floating_session_id_var.reset(session_token)

    # ── 8. Extract final text ─────────────────────────────────────────────────
    response_text: str | None = None
    for msg in reversed(result.messages):
        if msg.role == "assistant":
            texts = [b.text for b in msg.content if isinstance(b, TextBlock)]
            if texts:
                response_text = " ".join(texts)
                break

    # ── 9. Persist messages ────────────────────────────────────────────────────
    user_msg_id = await _persist_messages(
        session_id=session_id,
        user_text=user_text,
        assistant_text=response_text,
        user_content=None,
        assistant_content=None,
        usage=result.usage,
        db_session=db_session,
    )

    # ── 9b. Cost event recording ──────────────────────────────────────────────
    # Derive provider/model from adapter type — never propagate failures.
    try:
        from artemis.providers.claude_code.adapter import ClaudeCodeAdapter

        _fa_provider = "claude-code" if isinstance(adapter, ClaudeCodeAdapter) else "anthropic"
        _fa_model = getattr(adapter, "_default_model", "claude-sonnet-4-6") or "claude-sonnet-4-6"
        _fa_path = "cli" if isinstance(adapter, ClaudeCodeAdapter) else "api"
        import artemis.db as _cost_db

        async with _cost_db.SessionLocal() as _cost_session:
            await record_cost_event(
                _cost_session,
                provider=_fa_provider,
                model=_fa_model,
                provider_path=_fa_path,
                feature_tag="floating_artemis",
                input_tokens=result.usage.input_tokens,
                output_tokens=result.usage.output_tokens,
                cache_creation_input_tokens=result.usage.cache_creation_input_tokens,
                cache_read_input_tokens=result.usage.cache_read_input_tokens,
                source_kind="fa_message",
                session_id=session_id,
            )
            await _cost_session.commit()
    except Exception:
        logger.warning(
            "cost_event recording failed for FA session_id=%s", session_id, exc_info=True
        )

    # ── 9c. M3: auto-write conversation drawer ────────────────────────────────
    # Failure-isolated: drawer write NEVER breaks chat.
    if user_msg_id is not None and response_text is not None:
        try:
            await write_turn_drawer(
                user_msg_id=user_msg_id,
                user_text=user_text,
                assistant_text=response_text,
                agent_id=session_ctx.agent_id,
                speaker_name=speaker_name,
                speaker_id=speaker_id,
            )
        except Exception:
            logger.warning(
                "M3 turn-drawer write failed session_id=%s msg_id=%s",
                session_id,
                user_msg_id,
                exc_info=True,
            )

    # ── 9d. P6: fire-and-forget trace capture ────────────────────────────────
    # Non-blocking; failure is swallowed inside capture_trace. Records a
    # structured per-turn trace row for the self-evolution data foundation.
    try:
        _fa_provider = (
            "claude-code" if "ClaudeCodeAdapter" in type(adapter).__name__ else "anthropic"
        )
        _fa_model = getattr(adapter, "_default_model", None) or "claude-sonnet-4-6"
        # OBS-1: merges the Anthropic ToolUseBlock scan with the claude-code
        # stream-json tool_calls the adapter reports via result.metadata —
        # see _collect_tools_used for why both sources exist.
        _tools_used = _collect_tools_used(result)
        capture_trace(
            agent_id=session_ctx.agent_id,
            # Agent-neutral surface label: handle_turn is the shared conversational
            # turn engine for ALL agents (Artemis/Callie/Kai/…). The specific agent
            # is in agent_id; the surface (slack vs in-app) is derivable from session_id.
            feature_tag="agent_chat",
            session_id=session_id,
            provider=_fa_provider,
            model=_fa_model,
            input_summary=user_text[:500] if user_text else None,
            tools_used=_tools_used,
            output_summary=response_text[:500] if response_text else None,
            outcome="success",
            latency_ms=elapsed_ms(_turn_start),
            input_tokens=result.usage.input_tokens if result.usage else None,
            output_tokens=result.usage.output_tokens if result.usage else None,
            owner_user_id=owner_user_id,
        )
    except Exception:
        logger.debug(
            "P6 trace capture setup failed (non-fatal) session_id=%s", session_id, exc_info=True
        )

    # ── 10. Broadcast completion ──────────────────────────────────────────────
    await _broadcast(
        session_id,
        {
            "type": "floating_artemis.turn_complete",
            "session_id": session_id,
            "stop_reason": result.stop_reason,
        },
    )

    return TurnResult(
        session_id=session_id,
        response_text=response_text,
        stop_reason=result.stop_reason,
        usage=result.usage,
    )


# ── Tool-confirm continuation ─────────────────────────────────────────────────


async def resume_after_confirm(
    *,
    session_id: str,
    tool_use_id: str,
    decision: str,
    adapter: ModelAdapter | None = None,
    db_session: Any | None = None,
    trusted_agent_id: str | None = None,
) -> TurnResult:
    """Resume a suspended turn after operator confirms or cancels a layer-3/4 tool.

    Retrieves pending confirmation, executes (or cancels) the tool, then
    reattaches the conversation and runs to completion.

    Parameters
    ----------
    trusted_agent_id:
        M3 identity binding: when set (web-turn path), this value overrides the
        persisted session metadata for scope gating. Must be derived from the
        live caller's verified identity.  When None (Slack / tests), session
        metadata is used with a fail-closed default of "callie".
    """
    pending = confirmation_store.get(tool_use_id)
    if pending is None:
        raise ValueError(f"No pending confirmation for tool_use_id={tool_use_id!r}")

    # Execute or cancel the tool
    if decision == "run":
        # M3: load session context to get agent_id + surfaces for scope gating.
        # trusted_agent_id (from the live caller's identity) overrides persisted metadata.
        # query_memory is layer-1 and never reaches resume_after_confirm, but we
        # gate consistently in case future layer-2+ tools read memory.
        _resume_agent_id: str | None = None
        _resume_surfaces: set[str] = set()
        try:
            # Mirror the main turn path: load real surfaces first so that
            # surface-gated tools (okr, writing-rules, marketing, jira, granola)
            # are included in the registry — and integration tools (gcal, gmail,
            # slack) are always registered unconditionally via
            # build_authorized_tool_registry.
            try:
                _status = await get_status()
                _surfaces_list = (
                    _status.get("available_surfaces", []) if isinstance(_status, dict) else []
                )
                _resume_surfaces = set(_surfaces_list if isinstance(_surfaces_list, list) else [])
            except Exception:
                _resume_surfaces = set()

            _resume_session_ctx = await _load_session_context(
                session_id=pending.session_id,
                db_session=db_session,
                all_surfaces=_resume_surfaces,
                trusted_agent_id=trusted_agent_id,
            )
            _resume_agent_id = _resume_session_ctx.agent_id
            # Use the surfaces resolved by the session context (may differ from
            # the raw status list after per-session filtering).
            _resume_surfaces = _resume_session_ctx.available_surfaces
        except Exception:
            logger.debug("resume_after_confirm: could not load session context for agent_id")

        # Build the registry from the single canonical source so it is always
        # in sync with the main turn path (includes gcal, gmail, slack, jira,
        # granola — not just the core/okr/writing/marketing subset).
        auth_registry = build_authorized_tool_registry(
            _resume_surfaces,
            agent_id=_resume_agent_id,
        )

        entry = auth_registry.get(pending.tool_name)
        if entry is None:
            tool_result_content = f"Tool '{pending.tool_name}' not found."
            is_error = True
        else:
            try:
                tool_result_content = await entry.impl(pending.tool_input)
                is_error = False
            except Exception as exc:
                tool_result_content = f"{type(exc).__name__}: {exc}"
                is_error = True
    else:
        tool_result_content = "Operator cancelled this action."
        is_error = False

    confirmation_store.resolve(tool_use_id, decision)

    # Build result and resume
    tool_result_block = ToolResultBlock(
        tool_use_id=tool_use_id,
        content=tool_result_content,
        is_error=is_error,
    )
    prior_blocks = [
        ToolResultBlock(
            tool_use_id=str(block.get("tool_use_id", "")),
            content=str(block.get("content", "")),
            is_error=bool(block.get("is_error", False)),
        )
        for block in pending.prior_tool_results
    ]
    tool_result_blocks: list[TextBlock | ToolUseBlock | ToolResultBlock] = [
        *prior_blocks,
        tool_result_block,
    ]

    # Load current history and append the tool_result
    # M3: pass trusted_agent_id so scope gating uses live identity, not stale metadata.
    session_ctx = await _load_session_context(
        session_id=session_id,
        db_session=db_session,
        all_surfaces=set(),
        trusted_agent_id=trusted_agent_id,
    )
    history = await _load_message_history(
        session_id=session_id,
        db_session=db_session,
        session_metadata=session_ctx.metadata,
    )

    # Append a user message containing the tool_result (protocol: tool results are user-role)
    tool_result_msg = Message(role="user", content=tool_result_blocks)
    messages = history + [tool_result_msg]

    if adapter is None:
        resolved = await _resolve_adapter(session_id=session_id, db_session=db_session)
        adapter = resolved if not isinstance(resolved, str) else AnthropicAdapter()

    await _broadcast(
        session_id,
        {
            "type": "floating_artemis.tool_completed",
            "session_id": session_id,
            "tool_use_id": tool_use_id,
            "decision": decision,
            "is_error": is_error,
        },
    )

    session_token = floating_session_id_var.set(session_id)
    # SECURITY (M3): bind the subprocess's memory scope to the TRUSTED agent_id
    # (session_ctx.agent_id derives from the live caller's identity), not persisted
    # session metadata — so a non-owner turn on an owner session can't read owner memory.
    trusted_token = floating_trusted_agent_id_var.set(session_ctx.agent_id)
    try:
        agent_profile = load_agent_profile(session_ctx.agent_id)
        result = await run_turn(
            adapter=adapter,
            messages=messages,
            system=agent_profile.persona_core,
        )
    except Exception as exc:
        await _broadcast(
            session_id,
            {"type": "floating_artemis.failed", "session_id": session_id, "error": str(exc)},
        )
        raise
    finally:
        floating_trusted_agent_id_var.reset(trusted_token)
        floating_session_id_var.reset(session_token)

    response_text: str | None = None
    for msg in reversed(result.messages):
        if msg.role == "assistant":
            texts = [b.text for b in msg.content if isinstance(b, TextBlock)]
            if texts:
                response_text = " ".join(texts)
                break

    if response_text:
        await _broadcast(
            session_id,
            {"type": "floating_artemis.message", "session_id": session_id, "text": response_text},
        )

    await _persist_messages(
        session_id=session_id,
        user_text=None,
        assistant_text=response_text,
        user_content=_serialize_blocks(tool_result_msg.content),
        assistant_content=None,
        usage=result.usage,
        db_session=db_session,
    )

    await _broadcast(
        session_id,
        {"type": "floating_artemis.turn_complete", "session_id": session_id},
    )

    return TurnResult(
        session_id=session_id,
        response_text=response_text,
        stop_reason=result.stop_reason,
        usage=result.usage,
    )


# ── Private helpers ───────────────────────────────────────────────────────────


class _PendingConfirmationError(BaseException):  # noqa: N818 N818 — intentional non-error naming
    """Raised (not really an error) when a layer-3/4 tool is encountered."""

    def __init__(
        self, tool_use_id: str, tool_name: str, tool_input: dict[str, Any], layer: int
    ) -> None:
        super().__init__(f"tool_pending:{tool_use_id}")
        self.is_tool_pending = True
        self.tool_use_id = tool_use_id
        self.tool_name = tool_name
        self.tool_input = tool_input
        self.layer = layer
        self.prior_tool_results: list[ToolResultBlock] = []
        self.assistant_message: Message = Message(role="assistant", content=[])
        self.usage = Usage()


def _build_intercepting_tool_registry(
    auth_registry: AuthorizedToolRegistry,
    session_id: str,
    agent_id: str | None = None,
) -> ToolRegistry:
    """Wrap authorized tools into a plain ToolRegistry.

    Layer 3/4 tools get a wrapper impl that raises _PendingConfirmationError
    instead of executing. The loop catches this (via exception), stores pending
    state, and suspends.

    ``agent_id`` is threaded into the ``query_memory`` wrapper so the provenance
    re-run in ``_emit_memory_read_event`` is subject to the same M3 scope gating.
    """
    plain = ToolRegistry()
    for entry in auth_registry.all_entries():
        if entry.layer <= 2:
            if entry.tool.name == "query_memory":
                # Wrap to emit MemoryReadEvent after retrieval (inspector wiring).
                _orig_impl = entry.impl

                async def _query_memory_with_emit(
                    inp: dict[str, Any],
                    _impl: Any = _orig_impl,
                    _sid: str = session_id,
                    _aid: str | None = agent_id,
                ) -> str:
                    result_str: str = await _impl(inp)
                    try:
                        await _emit_memory_read_event(_sid, inp, agent_id=_aid)
                    except Exception:
                        logger.debug("MemoryReadEvent emit failed", exc_info=True)
                    return result_str

                plain.register(entry.tool, _query_memory_with_emit)
            else:
                plain.register(entry.tool, entry.impl)
        else:
            # Capture layer/name for the closure
            _layer = entry.layer
            _name = entry.tool.name

            async def pending_impl(
                inp: dict[str, Any], _tool_name: str = _name, _layer_n: int = _layer
            ) -> str:
                tool_use_id = floating_tool_use_id_var.get()
                if not tool_use_id:
                    raise RuntimeError(f"Missing tool_use id for pending tool {_tool_name!r}")
                pending = PendingConfirmation(
                    session_id=session_id,
                    tool_use_id=tool_use_id,
                    tool_name=_tool_name,
                    tool_input=inp,
                    layer=_layer_n,
                )
                confirmation_store.add(pending)
                raise _PendingConfirmationError(
                    tool_use_id=tool_use_id,
                    tool_name=_tool_name,
                    tool_input=inp,
                    layer=_layer_n,
                )

            plain.register(entry.tool, pending_impl)
    return plain


_STAGED_TOOL_MESSAGE = (
    "STAGED — not yet applied. This action needs the operator's confirmation. "
    "Tell them plainly what will change and ask them to reply 'go' to apply, "
    "or 'no' to cancel."
)


def _build_auto_invoke_tool_registry(
    auth_registry: AuthorizedToolRegistry,
    session_id: str,
    agent_id: str | None = None,
) -> ToolRegistry:
    """Build a ToolRegistry for provider paths that cannot yield mid-turn.

    Layer-1/2 tools run immediately.  Layer-3/4 tools get a staging wrapper
    that creates a PendingConfirmation and returns a tool-result string asking
    the model to relay the proposal to the operator — no write ever happens
    inside this wrapper (approval-first guarantee).  The turn ends normally;
    the operator's 'go' / 'no' is resolved by resume_after_confirm.

    ``agent_id`` is threaded into the ``query_memory`` wrapper so the provenance
    re-run in ``_emit_memory_read_event`` is subject to the same M3 scope gating.
    """
    plain = ToolRegistry()
    for entry in auth_registry.all_entries():
        if entry.layer <= 2:
            if entry.tool.name == "query_memory":
                _orig_impl = entry.impl

                async def _query_memory_with_emit(
                    inp: dict[str, Any],
                    _impl: Any = _orig_impl,
                    _sid: str = session_id,
                    _aid: str | None = agent_id,
                ) -> str:
                    result_str: str = await _impl(inp)
                    try:
                        await _emit_memory_read_event(_sid, inp, agent_id=_aid)
                    except Exception:
                        logger.debug("MemoryReadEvent emit failed", exc_info=True)
                    return result_str

                plain.register(entry.tool, _query_memory_with_emit)
            else:
                plain.register(entry.tool, entry.impl)
        else:
            # Layer-3/4: staging wrapper — store a PendingConfirmation and
            # return a message instructing the model to ask the operator to
            # confirm.  Does NOT call entry.impl.
            _layer = entry.layer
            _name = entry.tool.name

            async def _staging_wrapper(
                inp: dict[str, Any],
                _tool_name: str = _name,
                _layer_n: int = _layer,
            ) -> str:
                tool_use_id = floating_tool_use_id_var.get() or uuid4().hex
                pending = PendingConfirmation(
                    session_id=session_id,
                    tool_use_id=tool_use_id,
                    tool_name=_tool_name,
                    tool_input=inp,
                    layer=_layer_n,
                )
                confirmation_store.add(pending)
                return _STAGED_TOOL_MESSAGE

            plain.register(entry.tool, _staging_wrapper)
    return plain


async def _load_message_history(
    *,
    session_id: str,
    db_session: Any | None,
    session_metadata: dict[str, Any] | None = None,
    max_messages: int = 40,
) -> list[Message]:
    """Load recent message history from the DB, token-budgeted."""
    try:
        import artemis.db as _db
        from artemis.floating_artemis.repository import list_messages_for_context

        cutover_at = parse_history_cutover_at(session_metadata)

        if db_session is not None:
            msgs = await list_messages_for_context(
                db_session,
                session_id,
                limit=max_messages,
                created_at_gte=cutover_at,
            )
        else:
            async with _db.SessionLocal() as session:
                msgs = await list_messages_for_context(
                    session,
                    session_id,
                    limit=max_messages,
                    created_at_gte=cutover_at,
                )

        result: list[Message] = []
        for m in msgs:
            content_blocks: list[TextBlock | ToolUseBlock | ToolResultBlock] = []
            for block_dict in m.content or []:
                btype = block_dict.get("type", "text")
                if btype == "text":
                    content_blocks.append(TextBlock(text=block_dict.get("text", "")))
                elif btype == "tool_use":
                    content_blocks.append(
                        ToolUseBlock(
                            id=block_dict.get("id", ""),
                            name=block_dict.get("name", ""),
                            input=block_dict.get("input", {}),
                        )
                    )
                elif btype == "tool_result":
                    content_blocks.append(
                        ToolResultBlock(
                            tool_use_id=block_dict.get("tool_use_id", ""),
                            content=block_dict.get("content", ""),
                            is_error=block_dict.get("is_error", False),
                        )
                    )
            if content_blocks:
                if isinstance(m.role, str) and m.role in ("user", "assistant", "system"):
                    role: Literal["user", "assistant", "system"] = cast(
                        Literal["user", "assistant", "system"], m.role
                    )
                else:
                    role = "user"
                result.append(Message(role=role, content=content_blocks))
        return result
    except Exception:
        logger.debug("Could not load message history for session %s", session_id)
        return []


async def _get_page_context_text(
    *,
    session_id: str,
    db_session: Any | None,
) -> str | None:
    """Get the latest page context for the session."""
    try:
        import artemis.db as _db
        from artemis.floating_artemis.repository import get_latest_page_context

        if db_session is not None:
            ctx = await get_latest_page_context(db_session, session_id)
        else:
            async with _db.SessionLocal() as session:
                ctx = await get_latest_page_context(session, session_id)

        if ctx is None:
            return None
        result = f"Page: {ctx.page}"
        if ctx.ref_id:
            result += f" (ref: {ctx.ref_id})"
        return result
    except Exception:
        return None


async def _persist_messages(
    *,
    session_id: str,
    user_text: str | None,
    assistant_text: str | None,
    user_content: list[dict[str, Any]] | None,
    assistant_content: list[dict[str, Any]] | None,
    usage: Usage,
    db_session: Any | None,
) -> int | None:
    """Persist user + assistant messages to the DB.

    Returns the user message's primary key (for M3 drawer anchoring), or None
    when no user message was written or persistence failed.
    """
    try:
        import artemis.db as _db
        from artemis.floating_artemis.repository import add_message, touch_session

        async def _do_persist(session: Any) -> int | None:
            user_msg_id: int | None = None
            effective_user_content = user_content
            if effective_user_content is None and user_text is not None:
                effective_user_content = [{"type": "text", "text": user_text}]
            if effective_user_content is not None:
                user_msg = await add_message(
                    session,
                    session_id=session_id,
                    role="user",
                    content=effective_user_content,
                )
                user_msg_id = user_msg.id
            effective_assistant_content = assistant_content
            if effective_assistant_content is None and assistant_text is not None:
                effective_assistant_content = [{"type": "text", "text": assistant_text}]
            if effective_assistant_content is not None:
                await add_message(
                    session,
                    session_id=session_id,
                    role="assistant",
                    content=effective_assistant_content,
                    cost_input_tokens=usage.input_tokens,
                    cost_output_tokens=usage.output_tokens,
                    cache_creation_input_tokens=usage.cache_creation_input_tokens,
                    cache_read_input_tokens=usage.cache_read_input_tokens,
                )
            await touch_session(session, session_id)
            await session.commit()
            return user_msg_id

        if db_session is not None:
            return await _do_persist(db_session)
        else:
            async with _db.SessionLocal() as session:
                return await _do_persist(session)
    except Exception:
        logger.debug("Could not persist messages for session %s", session_id, exc_info=True)
        return None
